# Generated by Django 3.2.3 on 2021-06-04 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoapp',
            name='items_added',
            field=models.CharField(max_length=200, null='True'),
        ),
    ]
